"""Add new clinic profile columns

Revision ID: 21dd559b8975
Revises: 
Create Date: 2026-05-16 17:49:51.065986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21dd559b8975'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('mci_number', sa.String(length=20), nullable=True))
    op.add_column('clinics', sa.Column('gstin', sa.String(length=15), nullable=True))
    op.alter_column('clinics', 'slug',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('clinics', 'degree',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('clinics', 'experience',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('clinics', 'doctor_photo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('clinics', 'clinic_photo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('clinics', 'meta_title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('clinics', 'meta_description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('clinics', 'about_doctor',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('clinics', 'services',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('clinics', 'consultation_fee',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_constraint('clinics_slug_key', 'clinics', type_='unique')
    op.drop_index('idx_clinics_slug', table_name='clinics')
    op.create_index(op.f('ix_clinics_slug'), 'clinics', ['slug'], unique=True)
    op.add_column('patients', sa.Column('consent_given', sa.Boolean(), nullable=False))
    op.add_column('patients', sa.Column('consent_timestamp', sa.DateTime(), nullable=True))
    op.add_column('patients', sa.Column('consent_given_by', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('is_minor', sa.Boolean(), nullable=True))
    op.add_column('patients', sa.Column('guardian_name', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('guardian_relationship', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('otp_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'otp_code')
    op.drop_column('users', 'email')
    op.drop_column('patients', 'guardian_relationship')
    op.drop_column('patients', 'guardian_name')
    op.drop_column('patients', 'is_minor')
    op.drop_column('patients', 'consent_given_by')
    op.drop_column('patients', 'consent_timestamp')
    op.drop_column('patients', 'consent_given')
    op.drop_index(op.f('ix_clinics_slug'), table_name='clinics')
    op.create_index('idx_clinics_slug', 'clinics', ['slug'], unique=False)
    op.create_unique_constraint('clinics_slug_key', 'clinics', ['slug'])
    op.alter_column('clinics', 'consultation_fee',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('clinics', 'services',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('clinics', 'about_doctor',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('clinics', 'meta_description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('clinics', 'meta_title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('clinics', 'clinic_photo',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('clinics', 'doctor_photo',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('clinics', 'experience',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('clinics', 'degree',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('clinics', 'slug',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('clinics', 'gstin')
    op.drop_column('clinics', 'mci_number')
    # ### end Alembic commands ###
